branches:
 only:
  - master

language: objective-c

addons:
 ssh_known_hosts: exbi.nvaccess.org

env:
 - version="2016.1pre-$TRAVIS_BUILD_NUMBER,${TRAVIS_COMMIT:0:8}" dmg="osara_$version.dmg"

before_install:
 # We get weird errors without --egg. No idea why.
 # The latest SCons 2.5.0.post1 is broken, so hard-code 2.5.0 for now.
 - sudo pip install --egg scons==2.5.0

install:
 - cd ci
 # Decrypt files.
 - openssl enc -aes-256-cbc -d -pass pass:$encFileKey -in ssh_id_rsa.enc -out ssh_id_rsa
 # Install ssh stuff.
 - cp ssh_id_rsa ~/.ssh/id_rsa
 - chmod 600 ~/.ssh/id_rsa
 - cd ..

script: scons version=$version

after_success:
 '(echo "{\"os\": \"mac\", \"version\": \"$version\", \"dmg\": \"$dmg\"}"; cat installer/$dmg) | ssh nvaccess@exbi.nvaccess.org osaraCiHook'
