version: "2018.1pre-{build}"

branches:
 only:
  - master

environment:
 PY_PYTHON: 2.7-32
 encFileKey:
  secure: hN4Qfteiu6qqPajSvT+vrPfVoazOY+MFAlwUt/kZSnM=

init:
 - ps:       Update-AppveyorBuild -Version ("$env:APPVEYOR_BUILD_VERSION," + $env:APPVEYOR_REPO_COMMIT.Substring(0, 8))
 # We get weird errors without --egg. No idea why.
 # The latest SCons 2.5.0.post1 is broken, so hard-code 2.5.0 for now.
 - py -m pip install --egg scons==2.5.0

clone_depth: 1

install:
 - cd ci
 # Decrypt files.
 - openssl enc -aes-256-cbc -d -pass pass:%encFileKey% -in ssh_id_rsa.enc -out ssh_id_rsa
 # Install ssh stuff.
 - copy ssh_id_rsa %userprofile%\.ssh\id_rsa
 - type ssh_known_hosts >> %userprofile%\.ssh\known_hosts
 - cd ..
 - git submodule update --init

build_script:
 - py c:\python27\scripts\scons.py version=%APPVEYOR_BUILD_VERSION% publisher="NV Access Limited"

artifacts:
 - path: installer\*.exe

deploy_script:
 - ps: |
     $exe = Get-ChildItem -Name installer\*.exe
     $data = @{
      os="win";
      jobId=$env:APPVEYOR_JOB_ID;
      version=$env:APPVEYOR_BUILD_VERSION;
      exe=$exe
     }
     ConvertTo-Json -InputObject $data -Compress | ssh osara@duralumin.jantrid.net osaraCiHook
